<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
	<NoWarn>$(NoWarn);1591</NoWarn>
	<UserSecretsId>159c2039-968c-4a1a-8691-5ecb0c629261</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BC.Shared\BC.Shared.csproj" />
    <ProjectReference Include="..\BCCuentas.Application\BCCuentas.Application.csproj" />
    <ProjectReference Include="..\BCCuentas.Infrastructure\BCCuentas.Infrastructure.csproj" />
  </ItemGroup>

</Project>
